apiVersion: v1
kind: Service
metadata:
  namespace: jenkins
  name: reserve-check-service
  labels:
    env: production
    tier: backend
    app: reserve-check-service
    name: reserve-check-service-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    env: production
    tier: backend
    app: reserve-check-service
    name: reserve-check-service-pod